spring:
  application:
    name: EClient
server:
  port: 8088
eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka},${EUREKA_URI:http://localhost:8081/eureka}
  instance:
    preferIpAddress: true
    